### ISSUE TITLE
Core dump at exit after switching from HWaccel to OpenGL

### ISSUE THREAD

**Issue by ColinPitrat** [ColinPitrat/caprice32#16]
Starting caprice32 with video driver 'Double size with hardware flip' and switching with the GUI to 'Open GL scaling' on my X1 Carbon, it works but at exit of Caprice32, I have the following core:

```
(gdb) bt
#0  0x00007ffff6b21735 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff6b2245d in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007fffed0e02aa in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#3  0x00007fffed3b6ffe in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#4  0x00007fffed369763 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#5  0x00007ffff07aa50f in ?? () from /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
#6  0x00007ffff0786bb9 in glXDestroyContext () from /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
#7  0x00007ffff7b7d1d2 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
#8  0x00007ffff7b80ffe in ?? () from /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
#9  0x00007ffff7b8120e in ?? () from /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
#10 0x00007ffff7b7395e in SDL_VideoQuit () from /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
#11 0x00007ffff7b4df75 in SDL_QuitSubSystem () from /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
#12 0x00007ffff7b4e01e in SDL_Quit () from /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0
#13 0x00007ffff6adf1a9 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#14 0x00007ffff6adf1f5 in exit () from /lib/x86_64-linux-gnu/libc.so.6
#15 0x000000000046e7fa in wGui::CapriceMenu::HandleMessage (this=0xba8b60, pMessage=0xb404e0) at src/gui/src/CapriceMenu.cpp:171
#16 0x00000000004ad431 in wGui::CMessageServer::DeliverMessage (this=0x7b3200) at src/gui/src/wg_message_server.cpp:147
#17 0x000000000049d86d in wGui::CApplication::Exec (this=0x7fffffffdd30) at src/gui/src/wg_application.cpp:311
#18 0x00000000004534db in showGui () at src/cap32.cpp:3030
#19 0x00000000004543b2 in cap32_main (argc=1, argv=0x7fffffffe0c8) at src/cap32.cpp:3318
#20 0x00000000004c1025 in main (argc=1, argv=0x7fffffffe0c8) at main.cpp:5
```

To be noted that the reverse (going from OpenGL to Double HW) results in having only the left half of the screen visible, the right half being black. Not sure if it's related or a separate issue.

**Comment by ColinPitrat** [comment]
This has long been fixed.
